export const ADD_QUESTIONS = "ADD_QUESTIONS";
export const INCREASE_QUESTION_COUNT = "INCREASE_QUESTION_COUNT";
export const DECREASE_QUESTION_COUNT = "DECREASE_QUESTION_COUNT";
export const ADD_ANSWER = "ADD_ANSWER";
